version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "nuget"
