name: Build WPF App (.NET 9)

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches: dev

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: ソースをチェックアウト
        uses: actions/checkout@v4

      - name: .NET 9 SDK をセットアップ
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: NuGet パッケージの復元
        run: dotnet restore YourProject.csproj

      - name: アプリケーションのビルド(Release)
        run: dotnet build YourProject.csproj --configuration Release --no-restore

      - name: 成果物のアップロード
        uses: actions/upload-artifact@v4
        with:
          name: WPF-App
          path: |
            **/bin/Release/net9.0-windows/
